backend:
  name: git-gateway
  branch: master
media_folder: gatsby/static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: static/blog
    create: true
    fields:
      - label: Type
        name: type
        widget: hidden
        default: blog
      - label: Date
        name: date
        widget: datetime
      - label: Title
        name: title
        widget: string
      - label: Featured Article
        name: isFeatured
        widget: boolean
      - label: Category
        name: category
        widget: select
        default: project
        options:
          - { label: Project, value: project }
          - { label: Personal, value: personal }
          - { label: Random, value: random }
      - label: Header Image
        name: image
        widget: image
      - label: Content
        name: body
        widget: markdown
