backend:
  name: git-gateway
  branch: master
media_folder: gatsby/static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: gatsby/static/blog
    create: true
    fields:
      - label: Type
        name: type
        widget: hidden
        default: blog
      - label: Date
        name: date
        widget: datetime
      - label: Title
        name: title
        widget: string
      - label: Featured Article
        name: isFeatured
        widget: boolean
      - label: Color
        name: color
        widget: select
        default: project
        options:
          - { label: Background, value: "#282a36" }
          - { label: Current Line, value: "#44475a" }
          - { label: Selection, value: "#44475a" }
          - { label: Foreground, value: "#f8f8f2" }
          - { label: Comment, value: "#6272a4" }
          - { label: Cyan, value: "#8be9fd" }
          - { label: Green, value: "#50fa7b" }
          - { label: Orange, value: "#ffb86c" }
          - { label: Pink, value: "#ff79c6" }
          - { label: Purple, value: "#bd93f9" }
          - { label: Red, value: "#ff5555" }
          - { label: Yellow, value: "#f1fa8c" }
          - { label: Dark Grey, value: "#303030" }
          - { label: Blue, value: "#0072b1" }
      - label: Category
        name: category
        widget: select
        default: project
        options:
          - { label: Project, value: project }
          - { label: Personal, value: personal }
          - { label: Random, value: random }
      - label: Header Image
        name: image
        widget: image
      - label: Content
        name: body
        widget: markdown
